export type Group =
  | 'Barlow'
  | 'Baldwin'
  | 'Platt'
  | 'McDonald'
  | 'Duckworth'
  | 'Webster'
  | 'Battersby'
  | 'Cropper'
  | 'Rovers'
  | 'Peacock'
  | 'Alahan'
  | 'Grimshaw'
  | 'Harris'
  | 'Nugent'
  | 'Other'

export interface Character {
  id: string
  name: string
  /** Wikipedia page title (may redirect to a section of a yearly list page). */
  wikiTitle: string
  group: Group
  /** Short one-liner shown in the sidebar. */
  blurb?: string
}

export type RelationshipType =
  | 'married'
  | 'engaged'
  | 'affair'
  | 'relationship'
  | 'fling'
  | 'parent'
  | 'sibling'
  | 'killed'
  | 'attempted-murder'
  | 'feud'

export interface Relationship {
  source: string
  target: string
  type: RelationshipType
  years?: string
  note: string
  /** Wikipedia page the claim is drawn from (title, not URL). */
  wiki?: string
}

/** Generated by scripts/fetch-wiki.ts */
export interface WikiInfo {
  title: string
  url: string
  portrayer?: string
  years?: string
  /** Path under /public, e.g. "avatars/ken-barlow.jpg"; absent if Wikipedia has no image. */
  image?: string
  spouses: string[]
}

export const ROMANTIC_TYPES: RelationshipType[] = ['married', 'engaged', 'affair', 'relationship', 'fling']

export const TYPE_META: Record<RelationshipType, { label: string; color: string; dash?: string; width: number }> = {
  married: { label: 'Married', color: '#e6b422', width: 3 },
  engaged: { label: 'Engaged', color: '#f28c28', width: 2.5 },
  affair: { label: 'Affair', color: '#e63946', dash: '8 5', width: 2.5 },
  relationship: { label: 'Relationship', color: '#ff7aa2', width: 2 },
  fling: { label: 'Fling / one-night stand', color: '#ff7aa2', dash: '2 5', width: 2 },
  parent: { label: 'Parent / child', color: '#8a8f98', width: 1.2 },
  sibling: { label: 'Siblings', color: '#8a8f98', dash: '4 4', width: 1.2 },
  killed: { label: 'Killed', color: '#111111', width: 3 },
  'attempted-murder': { label: 'Attempted murder', color: '#4a4a4a', dash: '6 4', width: 2.5 },
  feud: { label: 'Feud', color: '#6d7a8c', dash: '10 6', width: 1.8 },
}

export const GROUP_COLORS: Record<Group, string> = {
  Barlow: '#c94c4c',
  Baldwin: '#8e5aa6',
  Platt: '#3f88c5',
  McDonald: '#2a9d8f',
  Duckworth: '#e9c46a',
  Webster: '#f4a261',
  Battersby: '#e76f51',
  Cropper: '#9ccc65',
  Rovers: '#d4a373',
  Peacock: '#6a994e',
  Alahan: '#bc6c25',
  Grimshaw: '#5c80bc',
  Harris: '#a26769',
  Nugent: '#7f8c8d',
  Other: '#95a5a6',
}
